In [1]:
2 + 2

4

In [2]:
# Zdefiniuj klase Samochod z konstruktorem, ktorej instancje beda posiadaly
# atrybuty przekazywane jako argumenty
# marka, kolor, stan_licznika z domyslna wartoscia 0
# chcemy instancje w postaci bialy merol prosto z salonu (licznik = 0)
# druga instancje czarna bejca z 150000 na liczniku

In [3]:
class Samochod:
  def __init__(self, marka, kolor, stan_licznika = 0):
    self.marka = marka
    self.kolor = kolor
    self.licznik = stan_licznika

In [4]:
merc = Samochod("merc", "bialy")
bejca = Samochod("bejca", "czarna", stan_licznika=150000)

In [5]:
merc.licznik

0

In [6]:
merc.licznik += 50

In [7]:
merc.licznik

50

In [8]:
trasa = [10, 156, 106, 869, 6]

In [9]:
for fragment in trasa:
  bejca.licznik += fragment

In [ ]:
bejca.licznik += sum(trasa)

In [10]:
import numpy as np

Wektory (Arrays)
- 1 wymiarowe wektory
- 2 wymiarowa macierz - dwuwymiarowy wektor
- 3d, 4d, 5d, 10d

In [11]:
a = np.array([1, 2, 3, 4, 5])

In [12]:
type(a)

numpy.ndarray

In [13]:
a = np.arange(5)

In [14]:
a

array([0, 1, 2, 3, 4])

In [15]:
a.sum()

np.int64(10)

In [16]:
a.mean()

np.float64(2.0)

In [17]:
a.std()

np.float64(1.4142135623730951)

In [18]:
a.min()

np.int64(0)

In [19]:
a.max()

np.int64(4)

In [20]:
l = [1, 2, 3, 4, 5, 6]

In [21]:
l.mean()

AttributeError: 'list' object has no attribute 'mean'

In [22]:
a[0]

np.int64(0)

In [23]:
a[:2]

array([0, 1])

In [24]:
a[::-1]

array([4, 3, 2, 1, 0])

In [25]:
b = np.array([5, 6, 7, 8, 9])

In [28]:
a

array([0, 1, 2, 3, 4])

In [26]:
b

array([5, 6, 7, 8, 9])

In [27]:
a + b

array([ 5,  7,  9, 11, 13])

In [29]:
a - b

array([-5, -5, -5, -5, -5])

In [30]:
a * b

array([ 0,  6, 14, 24, 36])

In [31]:
a / b

array([0.        , 0.16666667, 0.28571429, 0.375     , 0.44444444])

In [32]:
a * 4.1

array([ 0. ,  4.1,  8.2, 12.3, 16.4])

In [33]:
a ** 2

array([ 0,  1,  4,  9, 16])

In [34]:
w = np.array([1, 2, "trzy"])

In [35]:
w

array(['1', '2', 'trzy'], dtype='<U21')

In [36]:
w * 3

TypeError: The 'out' kwarg is necessary. Use numpy.strings.multiply without it.

In [38]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [41]:
np.arange(3, 10, 2)

array([3, 5, 7, 9])

In [42]:
np.linspace(1, 2, 11)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

In [43]:
x = np.arange(1, 10).reshape(3, 3)

In [44]:
x


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
y = np.arange(1, 9).reshape(2,4)

In [46]:
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [47]:
np.zeros(100).reshape(10,10)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [49]:
z = np.arange(11,20).reshape(3,3)
z

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [50]:
x[1,1]

np.int64(5)

In [51]:
x[1,0]

np.int64(4)

In [52]:
x[0, 1]

np.int64(2)

In [53]:
x.shape

(3, 3)

In [54]:
x.ndim

2

In [55]:
x.size

9

In [56]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
x + 1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [59]:
x * z

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [60]:
x / z

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ],
       [0.41176471, 0.44444444, 0.47368421]])

In [61]:
x.sum()

np.int64(45)

In [62]:
x.sum(axis=0)

array([12, 15, 18])

In [84]:
x[0, 0] + x[1, 0] + x[2,0]

np.int64(12)

In [85]:
x[0, 1] + x[1,1] + x[2,1]

np.int64(15)

In [86]:
x[0, 2] + x[1,2] + x[2,2]

np.int64(18)

In [66]:
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [67]:
y.sum(axis=0)

array([ 6,  8, 10, 12])

In [68]:
y.sum(axis=1)

array([10, 26])

In [69]:
z

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [70]:
z.mean()

np.float64(15.0)

In [71]:
z.mean(axis=0)

array([14., 15., 16.])

In [74]:
q = np.arange(1, 13).reshape(2,2,3)

In [75]:
q

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [76]:
q.ndim

3

In [77]:
q[1, 0, 2]

np.int64(9)

In [78]:
rng = np.random.default_rng()

In [79]:
rng.normal(10, 1, 10)

array([10.3187967 , 10.25814449, 11.20138779, 10.3107191 ,  9.06154031,
        9.32588037, 10.26234972,  8.44107937, 10.598158  ,  8.69201235])

In [82]:
rng.uniform(0, 10, (10,10))

array([[2.70981994, 8.65269133, 9.02782593, 3.83069782, 3.67272051,
        9.95070721, 7.41326905, 9.09554593, 7.90431895, 5.78024832],
       [1.78351559, 6.39197818, 9.7385991 , 5.29194349, 0.58527626,
        8.64199742, 0.2348266 , 4.37632261, 4.1163392 , 7.92948416],
       [3.53164219, 7.50728619, 4.55408633, 2.31711437, 5.96637745,
        3.06169937, 4.27489693, 3.73838599, 2.56019959, 8.7608388 ],
       [5.59792843, 0.42953591, 8.6041336 , 1.10422569, 6.50107045,
        7.59264503, 0.27977075, 9.62350789, 2.02558211, 4.32450936],
       [3.20651343, 3.63113322, 5.72360201, 1.40575529, 4.87253016,
        8.94896814, 9.20411732, 4.69974668, 8.1168996 , 8.79670516],
       [3.19736918, 5.00381843, 3.41015259, 6.62239003, 0.61302373,
        4.89266109, 6.20896517, 1.49311285, 7.28122743, 6.09736139],
       [4.63579573, 8.9907785 , 6.86155576, 1.98756886, 4.44367425,
        0.8762048 , 5.24986745, 8.19596044, 0.81997161, 8.99479828],
       [0.54452543, 1.58279702, 1.0357291

In [83]:
rng.integers(0, 10, (10,10))

array([[7, 0, 7, 3, 5, 1, 6, 2, 2, 3],
       [7, 3, 3, 2, 5, 0, 6, 6, 6, 0],
       [3, 0, 9, 0, 6, 1, 0, 5, 3, 3],
       [3, 5, 1, 6, 6, 9, 0, 4, 9, 2],
       [7, 5, 9, 5, 4, 3, 8, 5, 1, 8],
       [2, 9, 0, 9, 6, 4, 8, 2, 3, 1],
       [1, 2, 1, 3, 3, 1, 9, 3, 2, 9],
       [1, 6, 1, 1, 4, 7, 2, 4, 8, 7],
       [5, 4, 7, 9, 6, 4, 3, 5, 0, 5],
       [1, 0, 1, 4, 7, 8, 9, 5, 3, 0]])